export const universities = [
    {
      name: "Latvijas Universitāte",
      location: "Rīga, Latvija",
      ranking: "#1",
      tuition: "€2,000/gadā",
      image: "https://www.lu.lv/fileadmin/user_upload/lu_portal/projekti/cfi/zinas/2018/csm_J035_6535afd9d9.jpg",
      programs: 150,
      students: "20k",
      acceptance: "30%",
      satisfaction: "85%",
      website: "https://www.lu.lv/"
    },
    {
      name: "Rīgas Tehniskā universitāte",
      location: "Rīga, Latvija",
      ranking: "#2",
      tuition: "€2,500/gadā",
      image: "https://www.rtu.lv/writable/public_files/b_RTU_1_rtu_kipsala.jpg",
      programs: 180,
      students: "15k",
      acceptance: "25%",
      satisfaction: "88%",
      website: "https://www.rtu.lv/"
    },
    {
      name: "Rīgas Stradiņa universitāte",
      location: "Rīga, Latvija",
      ranking: "#3",
      tuition: "€3,000/gadā",
      image: "https://www.researchlatvia.gov.lv/sites/default/files/styles/article_embed_image/public/2024-06/rsu.jpg?itok=O9Pka1Iz",
      programs: 120,
      students: "10k",
      acceptance: "20%",
      satisfaction: "90%",
      website: "https://www.rsu.lv/"
    },
    {
      name: "Daugavpils Universitāte",
      location: "Daugavpils, Latvija",
      ranking: "#4",
      tuition: "€1,500/gadā",
      image: "https://cdn.statically.io/img/cms.studyinlatvia.lv/q=90,f=auto,w=800/storage/app/uploads/public/648/360/d1e/648360d1ecfa7928954414.jpg",
      programs: 100,
      students: "8k",
      acceptance: "35%",
      satisfaction: "80%",
      website: "https://du.lv/"
    },
    {
      name: "Liepājas Universitāte",
      location: "Liepāja, Latvija",
      ranking: "#5",
      tuition: "€1,800/gadā",
      image: "https://enciklopedija.lv/api/image/thumbnail?name=c12cd06b5524-aaa7191d-22fe-4d74-accc-47da3b683825.jpg&size=title",
      programs: 90,
      students: "5k",
      acceptance: "40%",
      satisfaction: "82%",
      website: "https://www.rtu.lv/lv/liepaja"
    },
    {
      name: "Vidzemes Augstskola",
      location: "Valmiera, Latvija",
      ranking: "#6",
      tuition: "€1,600/gadā",
      image: "https://www.latvia.travel/sites/default/files/styles/mobile_promo/public/media_image/terbatas_iela_1.jpg?itok=b63W4sFm",
      programs: 70,
      students: "3k",
      acceptance: "45%",
      satisfaction: "78%",
      website: "https://va.lv/"
    },
    {
      name: "Ventspils Augstskola",
      location: "Ventspils, Latvija",
      ranking: "#7",
      tuition: "€1,700/gadā",
      image: "https://www.researchlatvia.gov.lv/sites/default/files/styles/article_embed_image/public/2024-06/vea.PNG?itok=2FEZy82x",
      programs: 60,
      students: "2.5k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.venta.lv/"
    },
    {
      name: "Rēzeknes Tehnoloģiju akadēmija",
      location: "Rēzekne, Latvija",
      ranking: "#8",
      tuition: "€1,400/gadā",
      image: "https://enciklopedija.lv/api/image/thumbnail?name=e75195395717-186219e6-4971-43a4-81e3-f690d3b790e2.jpg&size=multimedia",
      programs: 80,
      students: "4k",
      acceptance: "38%",
      satisfaction: "83%",
      website: "https://rta.lv/"
    },
    {
      name: "Banku Augstskola",
      location: "Rīga, Latvija",
      ranking: "#9",
      tuition: "€2,200/gadā",
      image: "https://upload.wikimedia.org/wikipedia/commons/8/86/Banku_augstskola_-_panoramio.jpg",
      programs: 50,
      students: "2k",
      acceptance: "60%",
      satisfaction: "75%",
      website: "https://www.ba.lv/lv/"
    },
    {
      name: "Biznesa augstskola Turība",
      location: "Rīga, Latvija",
      ranking: "#10",
      tuition: "€2,300/gadā",
      image: "https://www.turiba.lv/storage/files/dji-0265-hdr-1-1200x_.jpg?token=48c195e1e850ed3f7c5f3ee60a44bcba",
      programs: 60,
      students: "3k",
      acceptance: "55%",
      satisfaction: "77%",
      website: "https://www.turiba.lv/lv"
    },
    {
      name: "Latvijas Lauksaimniecības universitāte",
      location: "Jelgava, Latvija",
      ranking: "#11",
      tuition: "€1,900/gadā",
      image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Biron_Rezidenz.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.lbtu.lv/lv"
    },
    {
      name: "Rīgas Ekonomikas augstskola",
      location: "Rīga, Latvija",
      ranking: "#12",
      tuition: "€3,500/gadā",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Strelnieku_iela_4a.JPG/640px-Strelnieku_iela_4a.JPG",
      programs: 40,
      students: "1.5k",
      acceptance: "20%",
      satisfaction: "90%",
      website: "https://www.sseriga.edu/"
    },
    {
      name: "Jāzepa Vītola Latvijas Mūzikas akadēmija",
      location: "Rīga, Latvija",
      ranking: "#13",
      tuition: "€1,900/gadā",
      image: "https://lastatic.ams3.cdn.digitaloceanspaces.com/2018/10/Muzikas-akademija_LET_1475472.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.jvlma.lv/lv"
    },
    {
      name: "Latvijas Kūltūras akadēmija",
      location: "Rīga, Latvija",
      ranking: "#14",
      tuition: "€1,900/gadā",
      image: "https://lka.edu.lv/media/posts/post/image/Ludzas_iela_24_EIYnN5k.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.lka.edu.lv/lv/"
    },
    {
      name: "Latvijas Mākslas akadēmija",
      location: "Rīga, Latvija",
      ranking: "#15",
      tuition: "€1,900/gadā",
      image: "https://enciklopedija.lv/api/image/original?name=a3692a10b0e7-6bc8f992-4958-442c-8198-651e616ccb0b.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.lma.lv/lv"
    },
    {
      name: "Latvijas Jūras akadēmija",
      location: "Rīga, Latvija",
      ranking: "#16",
      tuition: "€1,900/gadā",
      image: "https://enciklopedija.lv/api/image/thumbnail?name=285bf258a28a-6bb21177-9980-48e5-8553-cbfaacc4ef37.jpg&size=title",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.rtu.lv/lv/lja"
    },
    {
      name: "Latvijas Nacionālā aizsardzības akadēmija",
      location: "Rīga, Latvija",
      ranking: "#17",
      tuition: "€1,900/gadā",
      image: "https://abiem.info/wp-content/uploads/2019/07/3-1.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.naa.mil.lv/lv"
    },
    {
      name: "Latvijas Sporta pedagoģijas akadēmija",
      location: "Rīga, Latvija",
      ranking: "#18",
      tuition: "€1,900/gadā",
      image: "https://www.lspa.lv/files/2020/LSPA4_30.05._sena.png",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.rsu.lv/rsu-lspa"
    },
    {
      name: "Rēzeknes Augstskola",
      location: "Rīga, Latvija",
      ranking: "#19",
      tuition: "€1,900/gadā",
      image: "https://www.ergolain.lv/wp-content/uploads/2017/05/Mokymo-%C4%AFstaigos-1-1024x694.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://rta.lv/"
    },
    {
      name: "Baltijas Starptautiskā akadēmija",
      location: "Rīga, Latvija",
      ranking: "#20",
      tuition: "€1,900/gadā",
      image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Baltic_International_Academy_Daugavpils_%282%29.JPG",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://bsa.edu.lv/index.php/lv/"
    },
    {
      name: "Latvijas Kristīgā akadēmija",
      location: "Rīga, Latvija",
      ranking: "#21",
      tuition: "€1,900/gadā",
      image: "https://viss.lv/dati/latvijas_kristiga_akademija/logo_latvijas_kristiga_akademija.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://kra.lv/"
    },
    {
      name: "Lutera Akadēmija",
      location: "Rīga, Latvija",
      ranking: "#22",
      tuition: "€1,900/gadā",
      image: "https://www.luteraakademija.lv/adz/im/RARZI.jpeg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.luteraakademija.lv/"
    },
    {
      name: "Ekonomikas un kultūras augstskola",
      location: "Rīga, Latvija",
      ranking: "#23",
      tuition: "€1,900/gadā",
      image: "https://f8.pmo.ee/iLEhUU7j_n0TLwVLpiOJbtHLlbU=/685x0/filters:format(webp)/nginx/o/2022/12/19/15034961t1h36ed.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.augstskola.lv/#gsc.tab=0"
    },
    {
      name: "Informācijas sistēmu menedžmenta augstskola",
      location: "Rīga, Latvija",
      ranking: "#24",
      tuition: "€1,900/gadā",
      image: "https://lh5.googleusercontent.com/p/AF1QipNUJ-VXNRoHssx_Nz570gU_R5IaBuicz0J-6h39=w408-h306-k-no",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://isma.lv/"
    },
    {
      name: "Baltijas Psiholoģijas un menedžmenta augstskola",
      location: "Rīga, Latvija",
      ranking: "#25",
      tuition: "€1,900/gadā",
      image: "https://photos.wikimapia.org/p/00/00/89/92/66_big.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://bsa.edu.lv/index.php/lv/"
    },
    {
      name: "Rīgas Starptautiskā ekonomikas un biznesa administrācijas augstskola",
      location: "Rīga, Latvija",
      ranking: "#26",
      tuition: "€1,900/gadā",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/RISEBA%2C_biznesa%2C_m%C4%81kslas_un_tehnolo%C4%A3iju_augstskola%2C_galven%C4%81_%C4%93ka.jpg/220px-RISEBA%2C_biznesa%2C_m%C4%81kslas_un_tehnolo%C4%A3iju_augstskola%2C_galven%C4%81_%C4%93ka.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://riseba.lv/"
    },
    {
      name: "Rīgas Juridiskā augstskola",
      location: "Rīga, Latvija",
      ranking: "#27",
      tuition: "€1,900/gadā",
      image: "https://www.rgsl.edu.lv/uploads/advanced-pages/lv/1039/header/3dae0a0f25323951a80a33a2c8e458d9.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.rgsl.edu.lv/lv"
    },
    {
      name: "Transporta un sakaru institūts",
      location: "Rīga, Latvija",
      ranking: "#28",
      tuition: "€1,900/gadā",
      image: "https://www.lk-group.lv/site-files/gallery/2020-06/1591340400_7b8e2c38293a7b22f00afb5a50df09ff.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://tsi.lv/lv/"
    },
    {
      name: "Rīgas Aeronavigācijas institūts",
      location: "Rīga, Latvija",
      ranking: "#29",
      tuition: "€1,900/gadā",
      image: "https://rai.lv/imgrai/dom_1.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.rai.lv/"
    },
    {
      name: "Biznesa vadības koledža",
      location: "Rīga, Latvija",
      ranking: "#30",
      tuition: "€1,900/gadā",
      image: "https://www.bvk.lv/wp-content/uploads/2024/06/bzinesa-vadibas-koledza-alberta-iela-13-riga-latvija.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://www.bvk.lv/"
    },
    {
      name: "Kosmetoloģijas koledža",
      location: "Rīga, Latvija",
      ranking: "#31",
      tuition: "€1,900/gadā",
      image: "https://lvportals.lv/wwwraksti//PR/2023/JULIJS/BILDES/765V7E7TA.JPEG",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://skk.lv/"
    },
    {
      name: "Latvijas Biznesa koledža",
      location: "Rīga, Latvija",
      ranking: "#32",
      tuition: "€1,900/gadā",
      image: "https://pic.la.lv/2015/09/biznesakoledza1.jpg",
      programs: 100,
      students: "7k",
      acceptance: "50%",
      satisfaction: "80%",
      website: "https://biznesakoledza.lv/"
    },
  ];